### ISSUE TITLE
start callback should not be called if we have error filled up

### ISSUE THREAD

**Issue by behzadev** [michaelcbrook/simpleUpload.js#4]
Hello, first thanks for this great plugin, it's really good.
I have a problem which is:

when for example we set: `allowedExts: ["jpg", "jpeg"],`, and the user selects a PDF file, the plugin calls start and error callbacks at the same time, but I think the start callback should be called only when the upload starts, not when it's already failed. or maybe we must have 2 callbacks for start, the first one fires when the user selects the file (current start callback method) and another one when the upload actually starts.
am I right or wrong?
is there anyway to implement this with the current version? I need my uploader to work in this way.

Thanks

**Comment by behzadev** [comment]
Can I know if we had error filled up in start method? like:

``` javascript
start: function(file){
    if(noError){
        alert('NOW UPLOAD STARTED ACTUALLY');
    }
}
```

**Comment by behzadev** [comment]
I guess I was looking for the init method!

**Comment by michaelcbrook** [comment]
No problem :)
