### ISSUE TITLE
Upload a file variable?

### ISSUE THREAD

**Issue by reedhaffner** [michaelcbrook/simpleUpload.js#9]
Hi, I'm trying to upload a variable which is a file. I need this because I'm attempting to encrypt (with CryptoJS) then upload it. I've tried `fileenc.simpleUpload("upload.php", {});`, but it throws an error saying `TypeError: fileenc.simpleUpload is not a function. (In 'fileenc.simpleUpload("/upload.php", {})', 'fileenc.simpleUpload' is undefined)`. Any help?

**Comment by michaelcbrook** [comment]
Yes, it's looking at `fileenc` as the namespace for the simpleUpload function, but it's not located there. That is why you are getting this error. It needs to be called in the format `$('#file').simpleUpload("upload.php")` where `$('#file')` is the jQuery selector of the file input element. If you don't have a file input and would rather submit files directly, you can instead call `$.fn.simpleUpload("upload.php", { files: files })` where `files` is an array of files. I suspect this may be what you are trying to accomplish.
